In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [25]:
from sklearn import datasets
# Load the diabetes dataset
diabetes = datasets.load_diabetes()

In [26]:
diabetes.keys()

print(diabetes.feature_names)

diabetes.DESCR

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']


'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - Age\n      - Sex\n      - Body mass index\n      - Average blood pressure\n      - S1\n      - S2\n      - S3\n      - S4\n      - S5\n      - S6\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttp://www4.stat.ncsu.edu/~boos/var.select/diabetes.ht

In [27]:
# Note while reading the description one should find the input variable (values are already scaled) and target variable .Read the description carefully.

diabetes.data

diabetes.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [28]:
# putting the dataset in Pandas DataFrame

import pandas as pd

df =pd.DataFrame(data=diabetes.data,columns=diabetes.feature_names)

print(df)

df['DiseaseProgression']=diabetes.target

          age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
5   -0.092695 -0.044642 -0.040696 -0.019442 -0.068991 -0.079288  0.041277   
6   -0.045472  0.050680 -0.047163 -0.015999 -0.040096 -0.024800  0.000779   
7    0.063504  0.050680 -0.001895  0.066630  0.090620  0.108914  0.022869   
8    0.041708  0.050680  0.061696 -0.040099 -0.013953  0.006202 -0.028674   
9   -0.070900 -0.044642  0.039062 -0.033214 -0.012577 -0.034508 -0.024993   
10  -0.096328 -0.044642 -0.083808  0.008101 -0.103389 -0.090561 -0.013948   
11   0.027178  0.050680  0.017506 -0.033214 -0.007073  0.045972 -0.065491   

In [29]:
x=diabetes.data
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [30]:
y=diabetes.target
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [31]:
x.shape

(442, 10)

In [32]:
y.shape

(442,)

In [33]:
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.33,random_state=45)

In [35]:
x_train.shape

(146, 10)

In [36]:
y_train.shape

(146,)

In [38]:
lg=LogisticRegression()

In [39]:
lg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [40]:
lg.score(x_train,y_train) #82%correct

0.0821917808219178

In [43]:
pred=lg.predict(x_test)
pred

array([ 68., 248., 248., 275.,  72., 248., 248., 275., 248., 275., 248.,
        68., 248., 248.,  72.,  72.,  72., 248., 248., 248.,  83., 275.,
        72., 275.,  83., 248.,  72.,  72.,  72., 113., 248., 248.,  72.,
       248.,  68., 248., 248., 248., 248., 248., 248., 248.,  83., 248.,
       275., 248., 275., 248.,  83.,  83.,  68., 248., 248., 275., 248.,
        72.,  72.,  72., 275., 248., 248., 113., 275., 275.,  68.,  83.,
        83., 248., 248., 248., 275.,  72., 248.,  72., 248., 248., 248.,
       248.,  72., 248.,  72.,  72.,  72.,  83.,  72., 248.,  72., 113.,
       113., 248., 248.,  83.,  83.,  72.,  72.,  72.,  72.,  72., 248.,
       248.,  72., 248.,  72.,  72., 248., 275., 275.,  72.,  72.,  72.,
        83.,  72.,  68., 248.,  72., 275.,  72.,  72., 113., 113.,  72.,
       248., 275., 248., 248., 248., 248.,  72., 113.,  68.,  72., 248.,
       275., 248., 248., 248., 248.,  72., 248.,  72.,  72.,  72., 248.,
       248., 248.,  72., 275.,  72., 248.,  72.,  7

In [45]:
print("accuracy_score:",accuracy_score(pred,y_test))

accuracy_score: 0.006756756756756757


In [48]:
print("confusion_matrix:",confusion_matrix(y_test,pred))

confusion_matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [49]:
print("classification_report:",classification_report(y_test,pred))

classification_report:               precision    recall  f1-score   support

        31.0       0.00      0.00      0.00         1
        37.0       0.00      0.00      0.00         1
        39.0       0.00      0.00      0.00         1
        40.0       0.00      0.00      0.00         1
        42.0       0.00      0.00      0.00         3
        43.0       0.00      0.00      0.00         1
        44.0       0.00      0.00      0.00         1
        47.0       0.00      0.00      0.00         2
        48.0       0.00      0.00      0.00         3
        49.0       0.00      0.00      0.00         3
        51.0       0.00      0.00      0.00         3
        52.0       0.00      0.00      0.00         4
        53.0       0.00      0.00      0.00         3
        54.0       0.00      0.00      0.00         1
        55.0       0.00      0.00      0.00         4
        57.0       0.00      0.00      0.00         1
        58.0       0.00      0.00      0.00         1
    

In [52]:
#To Save the predicted data into csv
df=pd.DataFrame(pred)
df
df.to_csv("Diabetes Prediction.csv")